version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ocr_exame_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: alterar_a_senha_depois
      POSTGRES_DB: sistema_ocr_exame
    ports:
      - "5432:5432"
    networks:
      - ocr_exame_network

  api:
    build: .
    container_name: ocr_exame_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:alterar_a_senha_depois@db:5432/sistema_ocr_exame
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - ocr_exame_network
    volumes:
      - .:/code
      - ./uploads:/code/uploads

networks:
  ocr_exame_network:
    driver: bridge