"""add webhook_url to exames

Revision ID: 6760b4f8eb70
Revises: 005_add_clinical_summary
Create Date: 2026-05-03 03:49:28.470047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6760b4f8eb70'
down_revision: Union[str, None] = '005_add_clinical_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.add_column('exames', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exames', 'webhook_url')
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'])
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    # ### end Alembic commands ###
