"""initial_microservice_migration

Revision ID: bdd6f0ee55bd
Revises: 
Create Date: 2026-02-14 22:40:38.363604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd6f0ee55bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('data_coleta', sa.Date(), nullable=True),
    sa.Column('laboratorio', sa.String(), nullable=True),
    sa.Column('url_documento', sa.String(), nullable=True),
    sa.Column('status_processamento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_patient_id'), 'exames', ['patient_id'], unique=False)
    op.create_table('resultados_biomarcadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exame_id', sa.UUID(), nullable=True),
    sa.Column('nome_marcador', sa.String(), nullable=False),
    sa.Column('valor_extraido', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('referencia_lab', sa.String(), nullable=True),
    sa.Column('status_alerta', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exame_id'], ['exames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_biomarcadores')
    op.drop_index(op.f('ix_exames_patient_id'), table_name='exames')
    op.drop_table('exames')
    # ### end Alembic commands ###
