"""add exame_batches and link to exames

Revision ID: c126e4eff94d
Revises: 6760b4f8eb70
Create Date: 2026-05-03 04:44:35.526609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.sa_types


# revision identifiers, used by Alembic.
revision: str = 'c126e4eff94d'
down_revision: Union[str, None] = '6760b4f8eb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exame_batches',
    sa.Column('id', app.core.sa_types.GUID(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('completed_files', sa.Integer(), nullable=True),
    sa.Column('failed_files', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exame_batches_patient_id'), 'exame_batches', ['patient_id'], unique=False)
    op.add_column('exames', sa.Column('is_digitally_signed', sa.Boolean(), nullable=True))
    op.add_column('exames', sa.Column('batch_id', app.core.sa_types.GUID(), nullable=True))
    op.create_foreign_key(None, 'exames', 'exame_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exames', type_='foreignkey')
    op.drop_column('exames', 'batch_id')
    op.drop_column('exames', 'is_digitally_signed')
    op.drop_index(op.f('ix_exame_batches_patient_id'), table_name='exame_batches')
    op.drop_table('exame_batches')
    # ### end Alembic commands ###
